CREATE TABLE CLUB (
    CLUBID INTEGER NOT NULL PRIMARY KEY, 
    CLUBNAME VARCHAR(25) NOT NULL, 
    CLUBREGULARMEETINGDAYS VARCHAR(25) NOT NULL, 
    CLUBREGULARMEETINGTIMES VARCHAR(25) NOT NULL, 
    CLUBPRESIDENT VARCHAR(25) NOT NULL, 
    CLUBMEMBERCOUNT INTEGER NOT NULL 
);