CREATE TABLE ROOMRESERVATION (
    ROOMRESERVATIONID INTEGER NOT NULL PRIMARY KEY, 
    ROOMID INTEGER NOT NULL, 
    FOREIGN KEY(RoomID) REFERENCES Room(RoomID),
    CLUBID INTEGER NOT NULL,
    FOREIGN KEY (ClubID) REFERENCES Club(ClubID),
    RESERVATIONSTARTDATETIME VARCHAR(25) NOT NULL, 
    RESERVATIONENDDATETIME VARCHAR(25) NOT NULL,  
    NUMBEROFGUESTS INTEGER NOT NULL
 );